modLoader="javafml"
loaderVersion="[30,)"

[[mods]]
modId="strangeplants"
version="1.15.1-0.0.1.0"
displayName="Strange Plants"
authors="Choco"
description='''
Various strange plants added to the world to diversify world generation and immerse the player into a more lush environment.
'''

[[dependencies.dogtags]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dogtags]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"
